### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by arHSM** [arHSM/lucid#1]
# lucid - Roadmap

## Overview

This issue outlines the tasks concerning lucid. It also describes the current state of lucid and gives a rough idea of the framework's stability.

lucid is divided into 7 parts at the surface level

- Core
  > The *core* of lucid is... well the Core, it's `no_std` and provides basic primitives and utilities used all over lucid.\
  > The Core also contains the layout engine and the style-sheet definitions.\
  > If you are [developing on a embedded system] the lucid core is your best friend!
- Component Kit
  > The component kit provided with lucid is a `no_std` kit with many components that the end-user can use. When the `camouflage` [cargo feature] is enabled the components mimic the target platform's equivalent components as closely as possible, you can force override the look of components by enabling features for platforms individually, viz, `macos`, `linux`, `windows`.
- Pane
  > Pane is a window creation and management framework which provides features favorable over using [`winit`] as well as easily integrates with lucid.\
  > Pane supports macOS, Linux, Windows, iOS, Android, Web!
- Vivid
  > Vivid is the [`wgpu`], [`glow`] & [`glutin`] implementation for *Pane* used by lucid.
- Clearglyph
  > Clearglyph is a pure-rust `no_std` [HarfBuzz] port, which is framework and platform agnostic. Additionally clearglyph provides text layout utilities such as [UAX#14] line break opportunities and line breaking for complex text such as Thai.
- Unitable
  > Unitable (short for Unicode Table) is a crate providing minimal perfect hash lookup tables for various [Unicode] related data used by *Clearglyph*.

## Roadmap

- [ ] Core
  - [ ] Traits
    - [ ] `Surface`
    - [ ] `Drawable`
    - [ ] `Component`
  - [ ] Graphics primitives (`Drawable`s)
    - [ ] `Line`
    - [ ] `Curve`
    - [ ] `Text`
    - [ ] `Rect`
    - [ ] `RectBounds`
  - [ ] Layout Engine *(these are part of style-sheet definitions but are handled by the layout engine)*
    - [ ] [`display: flex`]
      - [ ] [`flex-direction`]
      - [ ] [`flex-wrap`]
    - [ ] [`display: grid`]
      - [ ] [`grid-template-rows`]
      - [ ] [`grid-template-columns`]
      - [ ] [`grid-row-start`]
      - [ ] [`grid-column-start`]
      - [ ] [`grid-row-end`]
      - [ ] [`grid-column-end`]
    - [ ] Justify
      - [ ] [`justify-content`]
      - [ ] [`justify-items`]
      - [ ] [`justify-self`]
    - [ ] Align
      - [ ] [`align-content`]
      - [ ] [`align-items`]
      - [ ] [`align-self`]
    - [ ] [`gap`]
    - [ ] [`margin`]
    - [ ] [`padding`]
  - [ ] Style-sheet definitions
    - [ ] [`accent-color`]
    - [ ] [`animation`]
    - [ ] [`background-color`] *(path or base64 (non-svg) only)*
    - [ ] [gradients] *(non-repeating only)*
    - [ ] Background
      - [ ] [`background-image`]
      - [ ] [`background-origin`]
      - [ ] [`background-position`]
      - [ ] [`background-repeat`]
      - [ ] [`background-size`]
      - [ ] [`background-clip`]
    - [ ] Border
      - [ ] [`border`] *(`top, bottom, left, right`, `color, width, style`)*
      - [ ] [`border-radius`]
      - [ ] [`border-collapse`] *(optional)*
    - [ ] Caret
      - [ ] [`caret-color`]
      - [ ] [`caret-shape`]
    - [ ] [`clip-path`]
    - [ ] [`color`]
    - [ ] [`cursor`] *(handled by pane)*
    - [ ] Font *(few of these will be handled by clearglyph)*
      - [ ] [`font-family`]
      - [ ] [`font-feature-settings`]
      - [ ] [`font-kerning`]
      - [ ] [`font-size`]
      - [ ] [`font-style`]
      - [ ] [`font-synthesis`]
      - [ ] [`font-weight`]
    - [ ] Media
      - [ ] [`media-width`]
      - [ ] [`media-height`]
      - [ ] [`media-orientation`]
      - [ ] [`media-prefers-color-scheme`]
      - [ ] [`media-prefers-contrast`] *(optional)*
    - [ ] [`opacity`]
    - [ ] Outline
      - [ ] [`outline`]
      - [ ] [`outline-offset`]
    - [ ] [`box-shadow`] *(`outer` & `inner`, `color, offset, blur, spread`)*
    - [ ] Text *(few of these will be handled by clearglyph)*
      - [ ] [`text-align`]
      - [ ] [`letter-spacing`]
      - [ ] [`line-height`]
      - [ ] [`line-break`]
      - [ ] [`word-break`]
      - [ ] [`word-spacing`]
      - [ ] [`text-orientation`]
      - [ ] [`writing-mode`]
      - [ ] [`text-decoration`]
      - [ ] [`text-underline-offset`] *(optional implementations for over-line and line-through too? that would introduce inconsistency with web implementation)*
    - [ ] [`transform`] *(`rotate`, `translate`, `scale` & `skew` only, this property doesn't affect layout it is purely applied at render instead of at layout)*
    - [ ] [`user-select`]
- [ ] Component Kit
  - [ ] Content
    - [ ] Image
    - [ ] Text Views
  - [ ] Layout & Organization
    - [ ] Grid
    - [ ] HStack
    - [ ] VStack
    - [ ] Tab Views
    - [ ] Lists
    - [ ] Tables
  - [ ] Menus & Actions
    - [ ] Button
    - [ ] Context Menus
    - [ ] Menus
    - [ ] Pop-up Buttons
    - [ ] Pull-down Buttons
    - [ ] Toolbars
  - [ ] Navigation
    - [ ] Search Input
    - [ ] Tab Bars
  - [ ] Presentation
    - [ ] Action Sheet
    - [ ] Alert
    - [ ] Confirmation
    - [ ] Page Control
    - [ ] Panel
    - [ ] Popover
    - [ ] Sheet
  - [ ] Selection & Input
    - [ ] Checkbox
    - [ ] Color Picker
    - [ ] Combo Boxes
    - [ ] Date Picker
    - [ ] Digit Entry
    - [ ] Image Input
    - [ ] Radio Button
    - [ ] Scroll Picker
    - [ ] Slider
    - [ ] Stepper
    - [ ] Tab Buttons
    - [ ] Text Input
    - [ ] Toggle
  - [ ] Status
    - [ ] Gauge
    - [ ] Progress Bar
    - [ ] Throbber (Progress Ring)
- [ ] Pane
  - [ ] Window & Sub-window creation
  - [ ] Native menus
    - [ ] Context Menu
    - [ ] Menu Bar
  - [ ] Keyboard Input
    - [ ] <https://www.w3.org/TR/uievents/#events-keyboardevents>
    - [ ] IME and dead key
  - [ ] Mouse, Pointer (touch/pen) Input
    - [ ] Motion
    - [ ] Click
    - [ ] Scroll
  - [ ] Cursor
    - [ ] Custom Cursor *([`cursor`])*
    - [ ] Locking, confining and force changing position
  - [ ] Touch & Multi-touch
  - [ ] Gamepad/Joystick Input *(optional)*
  - [ ] Gyroscope & Accelerometer Input
  - [ ] DPI scaling Information
  - [ ] System Clipboard
  - [ ] File Dialog
  - [ ] [`raw-window-handle`] Integration
  - [ ] Toggleable Window Decorations
  - [ ] Window Resizing *(snapping?)*
  - [ ] Transparent Background
  - [ ] States
    - [ ] Creating Full-screen/Maximized/Minimized/Default windows
    - [ ] Toggling Full-screen/Maximized/Minimized/Default states
  - [ ] Monitor Information
    - [ ] Resolution
    - [ ] Refresh Rate
    - [ ] Bit Depth
    - [ ] Primary/Secondary
- [ ] Vivid
  - [ ] WGPU
    - [ ] `Line`
      - [ ] Color
      - [ ] Opacity
    - [ ] `Curve`
      - [ ] Border
      - [ ] Fill
      - [ ] Opacity
    - [ ] `Rect`
      - [ ] Background
        - [ ] Background Color
        - [ ] Background Image
        - [ ] Background Image Positioning
        - [ ] Background Image Repetition
        - [ ] Background Image Scaling
          - [ ] Nearest Neighbor
          - [ ] Bi-linear
          - [ ] Bi-cubic
        - [ ] Background Clip
      - [ ] Border
        - [ ] Border
        - [ ] Border Radius
      - [ ] Outline
        - [ ] Outline
        - [ ] Outline Offset
      - [ ] Shadow
      - [ ] Opacity
    - [ ] `Text`
      - [ ] Color
      - [ ] Opacity
      - [ ] Text Decoration
      - [ ] Text Decoration Offset
- [ ] Clearglyph
  - [ ] HarfBuzz
    - [ ] Core
      - [ ] Blob: `hb-blob`
      - [ ] Buffer: `hb-buffer`
      - [ ] Common: `hb-common`
      - [ ] Features: `hb-features`
      - [ ] Draw: `hb-draw`
      - [ ] Paint: `hb-paint`
      - [ ] Face: `hb-face`
      - [ ] Font: `hb-font`
      - [ ] Shape Plan: `hb-shape-plan`
      - [ ] Shape: `hb-shape`
      - [ ] Unicode: `hb-unicode`
      - [ ] Version: `hb-version`
    - [ ] Open Type
      - [ ] Color: `hb-ot-color`
      - [ ] Font: `hb-ot-font`
      - [ ] Layout: `hb-ot-layout`
      - [ ] Math: `hb-ot-math`
      - [ ] Meta: `hb-ot-meta`
      - [ ] Metrics: `hb-ot-metrics`
      - [ ] Name: `hb-ot-name`
      - [ ] Shape: `hb-ot-shape`
      - [ ] Variation: `hb-ot-var`
    - [ ] Apple Advanced Typography:
      - [ ] AAT Layout: `hb-aat-layout`
    - [ ] Style:
      - [ ] Style: `hb-style`
    - [ ] Subset:
      - [ ] Subset: `hb-subset`
  - [ ] Layout *([`icu4x`] for this?)*
    - [ ] UAX#14
    - [ ] Complex Line Break
      - [ ] Thai
      - [ ] Burmese
      - [ ] Khmer
      - [ ] Lao
    - [ ] [BiDi]
    - [ ] [Japanese Text Layout]
- [ ] Unitable
  - [ ] [Scripts]
  - [ ] [General Categories]
  - [ ] [Canonical Combining Class]
  - [ ] [Decomposition Mappings]
  - [ ] [Composition Mappings]
  - [ ] [BiDi Mirroring Glyphs]
  - [ ] [Emoji Extended Pictographic]
  - [ ] [East Asian Width] *(not needed if we're using [`icu4x`] for layout)*
  - [ ] [Line Break] *(not needed if we're using [`icu4x`] for layout)*
  - [ ] [BiDi Class]
- [ ] Miscellaneous
  - [ ] Binary size optimizations
  - [ ] Performance & Start-up time optimizations
  - [ ] A11y integration with [AccessKit]
  - [ ] Platform clipboard integration & rich-text
  - [ ] Platform emoji picker
  - [ ] Grammar & Dictionary for text input
  - [ ] Font Fallback

[developing on a embedded system]: https://github.com/rust-embedded
[cargo feature]: https://doc.rust-lang.org/cargo/reference/features.html
[`winit`]: https://github.com/rust-windowing/winit
[`wgpu`]: https://github.com/gfx-rs/wgpu
[`glow`]: https://github.com/grovesNL/glow
[`glutin`]: https://github.com/rust-windowing/glutin
[HarfBuzz]: https://github.com/harfbuzz/harfbuzz
[UAX#14]: https://unicode.org/reports/tr14/
[Unicode]: https://home.unicode.org/
[IDE]: https://en.wikipedia.org/wiki/Integrated_development_environment

[`display: flex`]: https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_flex
[`flex-direction`]: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction
[`flex-wrap`]: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap
[`display: grid`]: https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_grid
[`grid-template-rows`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows
[`grid-template-columns`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
[`grid-row-start`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-start
[`grid-column-start`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start
[`grid-row-end`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-end
[`grid-column-end`]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-end
[`gap`]: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
[`margin`]: https://developer.mozilla.org/en-US/docs/Web/CSS/margin
[`padding`]: https://developer.mozilla.org/en-US/docs/Web/CSS/padding
[`justify-content`]: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
[`justify-items`]: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items
[`justify-self`]: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
[`align-content`]: https://developer.mozilla.org/en-US/docs/Web/CSS/align-content
[`align-items`]: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
[`align-self`]: https://developer.mozilla.org/en-US/docs/Web/CSS/align-self
[`accent-color`]: https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color
[`animation`]: https://developer.mozilla.org/en-US/docs/Web/CSS/animation
[`background-color`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
[gradients]: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient
[`background-image`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image
[`background-origin`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin
[`background-position`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
[`background-repeat`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat
[`background-size`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
[`background-clip`]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
[`border`]: https://developer.mozilla.org/en-US/docs/Web/CSS/border
[`border-radius`]: https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius
[`border-collapse`]: https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse
[`caret-color`]: https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color
[`caret-shape`]: https://drafts.csswg.org/css-ui-4/#propdef-caret-shape
[`clip-path`]: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
[`color`]: https://developer.mozilla.org/en-US/docs/Web/CSS/color
[`cursor`]: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
[`font-family`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
[`font-feature-settings`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
[`font-kerning`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning
[`font-size`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size
[`font-style`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style
[`font-synthesis`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
[`font-weight`]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
[`media-width`]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width
[`media-height`]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/height
[`media-orientation`]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation
[`media-prefers-color-scheme`]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
[`media-prefers-contrast`]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast
[`opacity`]: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
[`outline`]: https://developer.mozilla.org/en-US/docs/Web/CSS/outline
[`outline-offset`]: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset
[`box-shadow`]: https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
[`text-align`]: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
[`letter-spacing`]: https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing
[`line-height`]: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
[`line-break`]: https://developer.mozilla.org/en-US/docs/Web/CSS/line-break
[`word-break`]: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
[`word-spacing`]: https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing
[`text-orientation`]: https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation
[`writing-mode`]: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode
[`text-decoration`]: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration
[`text-underline-offset`]: https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset
[`transform`]: https://developer.mozilla.org/en-US/docs/Web/CSS/transform
[`user-select`]: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

[`raw-window-handle`]: https://github.com/rust-windowing/raw-window-handle
[`icu4x`]: https://github.com/unicode-org/icu4x
[BiDi]: https://www.w3.org/International/articles/inline-bidi-markup/uba-basics
[Japanese Text Layout]: https://www.w3.org/TR/jlreq/
[Scripts]: https://www.unicode.org/reports/tr44/#Scripts.txt
[General Categories]: https://www.unicode.org/reports/tr44/#General_Category
[Canonical Combining Class]: https://www.unicode.org/reports/tr44/#Canonical_Combining_Class
[Decomposition Mappings]: https://www.unicode.org/reports/tr44/#Decomposition_Mapping
[Composition Mappings]: https://www.unicode.org/reports/tr44/#Decomposition_Mapping
[BiDi Mirroring Glyphs]: https://www.unicode.org/reports/tr44/#Bidi_Mirroring_Glyph
[Emoji Extended Pictographic]: https://www.unicode.org/reports/tr44/#Extended_Pictographic
[East Asian Width]: https://www.unicode.org/reports/tr44/#East_Asian_Width
[Line Break]: https://www.unicode.org/reports/tr44/#Line_Break
[BiDi Class]: https://www.unicode.org/reports/tr44/#Bidi_Class
[AccessKit]: https://github.com/AccessKit/accesskit

**Comment by autocmts** [comment]
Hello @arHSM,

I recently had the opportunity to look through the 'lucid' project and I wanted to share some thoughts. 

Firstly, the idea behind 'lucid' - a multi-platform and robust GUI framework written in Rust - is quite promising. It's impressive that the framework aims to provide a solution for creating GUI applications for all major platforms including macOS, Linux, Windows, iOS, Android, and even embedded systems. The list of features, particularly the `no_std` core and `clearglyph`, make 'lucid' a compelling project to watch and potentially contribute to.

Speaking of contributions, I appreciate that you've created a clear set of contribution guidelines and have fostered a community through your personal Discord server. This is a great way to invite collaboration and discussion around the project.

The bug report and feature request templates are very well detailed, which should help in maintaining the quality of issues raised and in turn the overall quality of the project.

However, I had difficulty in accessing some of the code files in the repository. This could be a problem for potential contributors and users who want to understand the project better. If this is an issue on my end, any guidance would be appreciated. If not, it might be worth looking into this to ensure all parts of the project are accessible.

I'm excited to see where this project goes and I hope to contribute to it in the future. Keep up the great work!

Best,
Auto
